---
apiVersion: v1
kind: Deployment
metadata:
  name: {{ printf "%s-controller-manager" (include "adcs-issuer.fullname" .) | squote }}
  labels:
{{- include "adcs-issuer.labels" . | nindent 4}}
    app.kubernetes.io/component: controller-manager
spec:
  replicas: {{ .Values.controllerManager.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
{{- include "adcs-issuer.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
{{- include "adcs-issuer.labels" . | nindent 8 }}
        app.kubernetes.io/component: controller-manager
    spec:
      containers:
        - name: controller-manager
{{-
  include "adcs-issuer.containerImage"
  (dict "image" $.Values.controllerManager.manager.image "default" $.Chart.AppVersion)
  | nindent 10
-}}
{{- include "adcs-issuer.containerArgs" $.Values.controllerManager | nindent 10 }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
{{- include "adcs-issuer.containerEnv" $.Values.controllerManager | indent 12 }}
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
            - containerPort: 8080
              name: metrics
              protocol: TCP
{{- include "adcs-issuer.containerResources" $.Values.controllerManager.manager | indent 10 -}}
{{- include "adcs-issuer.containerReadinessProbe" $.Values.controllerManager.manager | indent 10 -}}
{{- include "adcs-issuer.containerLivenessProbe" $.Values.controllerManager.manager | indent 10 -}}
{{- include "adcs-issuer.containerSecurityContext" $.Values.controllerManager.manager | indent 10 }}
          volumeMounts:
{{- if .Values.controllerManager.enabledWebHooks }}
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
{{- end }}
{{- if .Values.controllerManager.enabledCaCerts }}
            - mountPath: /etc/ssl/certs/ca-certificates.crt
              name: ca-certificates
              subPath: ca-certificates.crt
              readOnly: true
{{- end }}
      volumes:
{{- if .Values.controllerManager.enabledWebHooks }}
        - name: cert
          secret:
            defaultMode: 420
            secretName: webhook-server-cert
{{- end }}
{{- if .Values.controllerManager.enabledCaCerts }}
        - name: ca-certificates
          secret:
            defaultMode: 420
            secretName: {{ squote .Values.controllerManager.caCertsSecretName }}
{{- end }}
      terminationGracePeriodSeconds: {{ .Values.controllerManager.terminationGracePeriodSeconds }}
{{- with $.Values.controllerManager.securityContext }}
      securityContext:
{{-     toYaml . | nindent 8 }}
{{- end }}
{{- with $.Values.controllerManager.tolerations }}
      tolerations:
{{-     toYaml . | nindent 8 }}
{{- end }}
{{- with $.Values.controllerManager.topologySpreadConstraints }}
      topologySpreadConstraints:
{{-   toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
{{- end }}
{{- if or $.Values.controllerManager.nodeAffinity $.Values.controllerManager.podAffinity $.Values.controllerManager.podAntiAffinity }}
      affinity:
{{-   with $.Values.controllerManager.nodeAffinity }}
        nodeAffinity:
{{-     toYaml . | nindent 10 }}
{{-   end }}
{{-   with $.Values.controllerManager.podAffinity }}
        podAffinity:
{{-     toYaml . | nindent 10 }}
{{-   end }}
{{-   with $.Values.controllerManager.podAntiAffinity }}
        podAntiAffinity:
{{-     toYaml . | nindent 10 }}
{{-   end }}
{{- end }}
