{{- if .Values.controllerManager.rbac.enabled }}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "adcs-issuer.fullname" . }}-manager-role
  labels:
    {{- include "adcs-issuer.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - adcs.certmanager.csf.nokia.com
    resources:
      - adcsissuers
      - adcsissuers/status
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - adcs.certmanager.csf.nokia.com
    resources:
      - adcsrequests
      - adcsrequests/status
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - adcs.certmanager.csf.nokia.com
    resources:
      - clusteradcsissuers
      - clusteradcsissuers/status
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cert-manager.io
    resources:
      - certificaterequests
      - certificaterequests/finalizers
      - certificaterequests/status
      - certificates/finalizers
    verbs:
      - get
      - list
      - patch
      - update
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "adcs-issuer.fullname" . }}-manager-rolebinding
  labels:
    {{- include "adcs-issuer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "adcs-issuer.fullname" . }}-manager-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.controllerManager.rbac.serviceAccountName | default (include "adcs-issuer.fullname" .) }}
    namespace: {{ .Release.Namespace }}

{{- end }}
