{{- if .Values.controllerManager.rbac.enabled }}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "adcs-issuer.fullname" . }}-proxy-role
  labels:
    {{- include "adcs-issuer.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "adcs-issuer.fullname" . }}-proxy-rolebinding
  labels:
    {{- include "adcs-issuer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "adcs-issuer.fullname" . }}-proxy-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.controllerManager.rbac.serviceAccountName | default (include "adcs-issuer.fullname" .) }}
    namespace: {{ .Release.Namespace }}

{{- end }}
