name: Test
on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          args: --timeout=3m
          version: v1.58
          skip-cache: true
          skip-save-cache: true
          cache-invalidation-interval: 15
      # TODO:
      #  - codecov (ideally with PR comment)
      #  - run `make test`
      #  - `make generate` & make sure there is no diff
      #  - vulnerability scanner?